### PR TITLE
Add LICENCE and README

### PR DESCRIPTION
**Pull request by a1300**
Dear @yanivefraim 

I came to your repository through your SO [answer](https://stackoverflow.com/questions/39609332/cannot-debug-node-child-process-using-node-native-debugger/39625861#39625861) and I found it very helpful. Thank you :+1: 

I wanted to add a little bit of description (mostly for me) if I need this in the future.
I also added a http://unlicense.org/ LICENCE so that your code can be used in other projects without worrying to much about the Licence model :slightly_smiling_face: 

All the best!
a1300

### CODE REVIEW

**Comment by a1300** [comment]
Dear @yanivefraim 

without a proper licence I can't use your code examples...
Could you merge the pull request or do you want to use another licence?

All the best!
a1300

**Comment by yanivefraim** [comment]
Thanks @a1300, this is cool! 

Did you try to use the new shiny [ndb](https://github.com/GoogleChromeLabs/ndb) for debugging?

**Review by yanivefraim — APPROVED** [review]

**Comment by a1300** [comment]
@yanivefraim thanks for merging! :+1: 

I will have a look at [ndb](https://github.com/GoogleChromeLabs/ndb) thanks!

**Comment by a1300** [comment]
Thanks @yanivefraim again for pointing me to [ndb](https://github.com/GoogleChromeLabs/ndb)!

[ndb](https://github.com/GoogleChromeLabs/ndb) is very powerful :slightly_smiling_face:

**Pull request merged**
